#spring.datasource.url=jdbc:h2:file:./data/socialcontracts
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.generate-ddl=true
#spring.h2.console.enabled=true
#springdoc.api-docs.path=/docs
#springdoc.swagger-ui.path=/swagger-ui
#server.error.include-stacktrace=never

spring:
    datasource:
        url: jdbc:h2:file:./data/socialcontracts
        driverClassName: org.h2.Driver
        username: sa
        password: 
    
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
    
    h2:
        console:
            enabled: true

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/PiraputangaDev

springdoc:
    api-docs:
        path: /docs
    swagger-ui:
        path: /swagger-ui

server:
    error:
        include-stacktrace: never
