server:
    port: 8081

spring:
    application.name: api-gateway
    cloud:
        gateway:
            routes:
                - id: socialactions-service
                  uri: lb://SOCIALACTIONS-SERVICE
                  predicates:
                    - Path=/socialactions
                - id: socialactions-service
                  uri: lb://SOCIALACTIONS-SERVICE
                  predicates:
                    - Path=/socialactions/**
                  filters:
                    - RewritePath=/socialactions/(?<id>.*), /socialactions/$\{id}
                    
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/PiraputangaDev
                    jwk-set-uri: http://localhost:8080/realms/PiraputangaDev/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost