spring:
    application:
        name: service-discovery

server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: https://service-discovery.onrender.com/eureka
    instance:
        prefer-ip-address: true