version: '0.1'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ./realms:/opt/keycloak/data/import
    ports:
      - 8080:8080